/* Generated by Continuation.js v0.1.0 */
(function (_$cont) {
  try {
    throw new Error('my error');
  } catch (err) {
    setTimeout(function () {
      console.log(err);
      _$cont();
    }, 1000);
    return;
  }
  _$cont();
}(function () {
  console.log('Done');
}));